INSERT INTO lessons (
  slug,
  track,
  lesson_order,
  chapter,
  title,
  description,
  objective,
  starter_code,
  completion_check_type,
  completion_check_value
)
VALUES
  (
    'hello-python',
    'Cơ bản lớp 6',
    1,
    'Cơ bản lớp 6 - Chương 1',
    'Làm quen với Python',
    'Làm quen với lệnh print và cách chương trình hiển thị kết quả đầu tiên.',
    'Viết lệnh print để chào Py-Bot.',
    '# Hãy viết mã của bạn bên dưới\nprint("Chào Py-Bot!")',
    'output_contains',
    'Chào Py-Bot!'
  ),
  (
    'print-multiple-lines',
    'Cơ bản lớp 6',
    2,
    'Cơ bản lớp 6 - Chương 1',
    'In nhiều dòng',
    'Học cách dùng nhiều lệnh print để tạo ra nhiều dòng kết quả.',
    'In ra hai dòng văn bản khác nhau.',
    'print("Xin chào")\nprint("Mình đang học Python")',
    'output_contains',
    'Mình đang học Python'
  ),
  (
    'variables-basic',
    'Cơ bản lớp 6',
    3,
    'Cơ bản lớp 6 - Chương 1',
    'Biến đầu tiên',
    'Biết cách tạo biến để lưu dữ liệu và dùng lại trong chương trình.',
    'Tạo biến name và in ra giá trị của nó.',
    'name = "Py-Bot"\nprint(name)',
    'output_contains',
    'Py-Bot'
  ),
  (
    'numbers-and-math',
    'Cơ bản lớp 6',
    4,
    'Cơ bản lớp 6 - Chương 1',
    'Số và phép tính',
    'Làm quen với số nguyên, cộng, trừ, nhân trong Python.',
    'Tính tổng của hai số và in kết quả.',
    'a = 7\nb = 5\nprint(a + b)',
    'output_contains',
    '12'
  ),
  (
    'strings-basic',
    'Cơ bản lớp 6',
    5,
    'Cơ bản lớp 6 - Chương 1',
    'Chuỗi ký tự',
    'Biết cách ghép chuỗi và hiển thị câu hoàn chỉnh.',
    'Ghép hai chuỗi và in ra câu chào.',
    'greeting = "Chào"\nname = "Py-Bot"\nprint(greeting + " " + name)',
    'output_contains',
    'Chào Py-Bot'
  ),
  (
    'input-simulation',
    'Cơ bản lớp 6',
    6,
    'Cơ bản lớp 6 - Chương 1',
    'Dữ liệu đầu vào mô phỏng',
    'Hiểu ý tưởng lấy dữ liệu từ người dùng thông qua biến mô phỏng.',
    'Dùng biến user_name và in ra lời chào cá nhân hóa.',
    'user_name = "Lan"\nprint("Xin chào, " + user_name)',
    'output_contains',
    'Xin chào, Lan'
  ),
  (
    'comparison-operators',
    'Cơ bản lớp 6',
    7,
    'Cơ bản lớp 6 - Chương 2',
    'Toán tử so sánh',
    'Làm quen với các phép so sánh như lớn hơn, nhỏ hơn, bằng nhau.',
    'So sánh hai số và in ra kết quả True hoặc False.',
    'score = 8\nprint(score >= 5)',
    'output_contains',
    'True'
  ),
  (
    'if-basic',
    'Cơ bản lớp 6',
    8,
    'Cơ bản lớp 6 - Chương 2',
    'Điều kiện if',
    'Tạo nhánh xử lý khi điều kiện đúng.',
    'Dùng if để in ra "Đạt" khi điểm lớn hơn hoặc bằng 5.',
    'score = 8\nif score >= 5:\n    print("Đạt")',
    'output_contains',
    'Đạt'
  ),
  (
    'if-else',
    'Cơ bản lớp 6',
    9,
    'Cơ bản lớp 6 - Chương 2',
    'Điều kiện if else',
    'Chương trình phản hồi khác nhau theo từng trường hợp.',
    'Viết điều kiện if else để kiểm tra điểm số.',
    'score = 8\nif score >= 5:\n    print("Qua bài")\nelse:\n    print("Làm lại")',
    'output_contains',
    'Qua bài'
  ),
  (
    'elif-branches',
    'Cơ bản lớp 6',
    10,
    'Cơ bản lớp 6 - Chương 2',
    'Nhiều nhánh với elif',
    'Biết cách xử lý nhiều trường hợp khác nhau bằng elif.',
    'Phân loại điểm thành giỏi, khá hoặc cần cố gắng.',
    'score = 8\nif score >= 9:\n    print("Giỏi")\nelif score >= 7:\n    print("Khá")\nelse:\n    print("Cần cố gắng")',
    'output_contains',
    'Khá'
  ),
  (
    'for-range',
    'Cơ bản lớp 6',
    11,
    'Cơ bản lớp 6 - Chương 3',
    'Vòng lặp for với range',
    'Lặp hành động nhiều lần mà không viết lại mã.',
    'Viết vòng lặp for chạy 3 lần.',
    'for i in range(3):\n    print("Lần lặp", i)',
    'output_contains',
    'Lần lặp 2'
  ),
  (
    'for-list',
    'Cơ bản lớp 6',
    12,
    'Cơ bản lớp 6 - Chương 3',
    'Duyệt danh sách bằng for',
    'Lặp qua từng phần tử trong một danh sách.',
    'In lần lượt các món đồ trong danh sách.',
    'items = ["bút", "vở", "thước"]\nfor item in items:\n    print(item)',
    'output_contains',
    'thước'
  ),
  (
    'while-loop',
    'Cơ bản lớp 6',
    13,
    'Cơ bản lớp 6 - Chương 3',
    'Vòng lặp while',
    'Hiểu cách lặp khi điều kiện còn đúng.',
    'Dùng while để đếm từ 1 đến 3.',
    'count = 1\nwhile count <= 3:\n    print(count)\n    count += 1',
    'output_contains',
    '3'
  ),
  (
    'break-continue',
    'Cơ bản lớp 6',
    14,
    'Cơ bản lớp 6 - Chương 3',
    'Break và continue',
    'Điều khiển vòng lặp bỏ qua hoặc dừng sớm.',
    'Dùng continue để bỏ qua số 3.',
    'for i in range(1, 6):\n    if i == 3:\n        continue\n    print(i)',
    'output_contains',
    '5'
  ),
  (
    'functions-basic',
    'Cơ bản lớp 6',
    15,
    'Cơ bản lớp 6 - Chương 4',
    'Hàm đầu tiên',
    'Gom các câu lệnh lặp lại vào hàm để tái sử dụng dễ dàng.',
    'Tạo hàm greet và gọi hàm.',
    'def greet(name):\n    print(f"Chào {name}!")\n\ngreet("Py-Bot")',
    'output_contains',
    'Chào Py-Bot!'
  ),
  (
    'functions-return',
    'Cơ bản lớp 6',
    16,
    'Cơ bản lớp 6 - Chương 4',
    'Giá trị trả về',
    'Biết cách dùng return để lấy kết quả từ hàm.',
    'Viết hàm cộng hai số và in kết quả trả về.',
    'def add(a, b):\n    return a + b\n\nprint(add(4, 6))',
    'output_contains',
    '10'
  ),
  (
    'function-parameters',
    'Cơ bản lớp 6',
    17,
    'Cơ bản lớp 6 - Chương 4',
    'Tham số hàm',
    'Truyền dữ liệu vào hàm thông qua tham số.',
    'Tạo hàm mô tả con vật nhận vào tên con vật.',
    'def describe_pet(name):\n    print("Đây là", name)\n\ndescribe_pet("mèo")',
    'output_contains',
    'Đây là mèo'
  ),
  (
    'lists-basic',
    'Cơ bản lớp 6',
    18,
    'Cơ bản lớp 6 - Chương 5',
    'Danh sách cơ bản',
    'Tạo list, truy cập phần tử và in dữ liệu.',
    'In phần tử đầu tiên của danh sách fruits.',
    'fruits = ["táo", "cam", "chuối"]\nprint(fruits[0])',
    'output_contains',
    'táo'
  ),
  (
    'lists-update',
    'Cơ bản lớp 6',
    19,
    'Cơ bản lớp 6 - Chương 5',
    'Thêm phần tử vào list',
    'Biết cách append để thêm dữ liệu mới vào danh sách.',
    'Thêm một phần tử mới vào list và in ra list.',
    'fruits = ["táo", "cam"]\nfruits.append("chuối")\nprint(fruits)',
    'output_contains',
    'chuối'
  ),
  (
    'list-slicing',
    'Cơ bản lớp 6',
    20,
    'Cơ bản lớp 6 - Chương 5',
    'Cắt danh sách',
    'Lấy một phần của list bằng slicing.',
    'In ra hai phần tử đầu tiên của list.',
    'numbers = [1, 2, 3, 4, 5]\nprint(numbers[:2])',
    'output_contains',
    '[1, 2]'
  ),
  (
    'strings-methods',
    'Nâng cao lớp 6',
    21,
    'Nâng cao lớp 6 - Chương 1',
    'Phương thức chuỗi',
    'Học cách dùng upper, lower và replace với chuỗi.',
    'Chuyển chuỗi thành in hoa và in ra.',
    'message = "python"\nprint(message.upper())',
    'output_contains',
    'PYTHON'
  ),
  (
    'dictionaries-basic',
    'Nâng cao lớp 6',
    22,
    'Nâng cao lớp 6 - Chương 1',
    'Từ điển cơ bản',
    'Lưu dữ liệu dạng key-value và đọc giá trị từ key.',
    'In tên từ dictionary student.',
    'student = {"name": "An", "age": 11}\nprint(student["name"])',
    'output_contains',
    'An'
  ),
  (
    'dictionaries-update',
    'Nâng cao lớp 6',
    23,
    'Nâng cao lớp 6 - Chương 1',
    'Cập nhật dictionary',
    'Thêm key mới và cập nhật dữ liệu trong dictionary.',
    'Thêm key city và in toàn bộ dictionary.',
    'student = {"name": "An"}\nstudent["city"] = "Hà Nội"\nprint(student)',
    'output_contains',
    'Hà Nội'
  ),
  (
    'nested-data',
    'Nâng cao lớp 6',
    24,
    'Nâng cao lớp 6 - Chương 1',
    'Dữ liệu lồng nhau',
    'Làm việc với dictionary chứa list.',
    'In ra môn học đầu tiên của học sinh.',
    'student = {"name": "An", "subjects": ["Toán", "Tin"]}\nprint(student["subjects"][0])',
    'output_contains',
    'Toán'
  ),
  (
    'import-math',
    'Nâng cao lớp 6',
    25,
    'Nâng cao lớp 6 - Chương 2',
    'Import module math',
    'Biết cách dùng module có sẵn trong Python.',
    'Import math và in căn bậc hai của 16.',
    'import math\nprint(math.sqrt(16))',
    'output_contains',
    '4.0'
  ),
  (
    'random-module',
    'Nâng cao lớp 6',
    26,
    'Nâng cao lớp 6 - Chương 2',
    'Module random',
    'Làm quen với việc dùng random để chọn dữ liệu ngẫu nhiên.',
    'Dùng random.choice để chọn một màu trong danh sách.',
    'import random\ncolors = ["đỏ", "xanh", "vàng"]\nprint(random.choice(colors))',
    'code_contains',
    'random.choice'
  ),
  (
    'mini-project-quiz',
    'Nâng cao lớp 6',
    27,
    'Nâng cao lớp 6 - Chương 3',
    'Mini project câu hỏi',
    'Kết hợp biến, điều kiện và in kết quả trong một chương trình nhỏ.',
    'Viết chương trình kiểm tra một câu trả lời đơn giản.',
    'answer = "python"\nif answer == "python":\n    print("Chính xác")\nelse:\n    print("Thử lại")',
    'output_contains',
    'Chính xác'
  ),
  (
    'mini-project-greeter',
    'Nâng cao lớp 6',
    28,
    'Nâng cao lớp 6 - Chương 3',
    'Mini project lời chào',
    'Kết hợp hàm và vòng lặp để tạo một chương trình hoàn chỉnh nhỏ.',
    'In ra 3 lời chào bằng hàm và vòng lặp.',
    'def greet(name):\n    print(f"Chào {name}!")\n\nfor _ in range(3):\n    greet("Py-Bot")',
    'output_contains',
    'Chào Py-Bot!'
  )
ON CONFLICT (slug) DO UPDATE SET
  track = EXCLUDED.track,
  chapter = EXCLUDED.chapter,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  objective = EXCLUDED.objective,
  starter_code = EXCLUDED.starter_code,
  completion_check_type = EXCLUDED.completion_check_type,
  completion_check_value = EXCLUDED.completion_check_value;
